# Generated by Django 4.1.13 on 2026-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenderID',
            fields=[
                ('gender_code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã giới tính')),
                ('gender_name', models.CharField(max_length=20, verbose_name='Tên giới tính')),
            ],
            options={
                'verbose_name': 'Danh mục Giới tính',
                'verbose_name_plural': 'Danh mục Giới tính',
            },
        ),
    ]
