# Generated by Django 4.1.13 on 2026-05-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='afg_kinderen_huishouden',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã số')),
                ('name', models.CharField(max_length=255, verbose_name='Trẻ em trong nhà (Children in household)')),
            ],
            options={
                'verbose_name': '8. Trẻ em trong nhà (afg_kinderen_huishouden)',
                'verbose_name_plural': '8. Trẻ em trong nhà (afg_kinderen_huishouden)',
            },
        ),
        migrations.CreateModel(
            name='AFG_sk2015',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã tầng lớp')),
                ('name', models.CharField(max_length=255, verbose_name='Tầng lớp xã hội (Social class 2015)')),
            ],
            options={
                'verbose_name': '9. Tầng lớp xã hội (AFG_sk2015)',
                'verbose_name_plural': '9. Tầng lớp xã hội (AFG_sk2015)',
            },
        ),
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã nhóm tuổi')),
                ('name', models.CharField(max_length=255, verbose_name='Nhóm tuổi (Age)')),
            ],
            options={
                'verbose_name': '6. Nhóm tuổi (Age)',
                'verbose_name_plural': '6. Nhóm tuổi (Age)',
            },
        ),
        migrations.CreateModel(
            name='BAS_bruto_jaarinkomen',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã thu nhập')),
                ('name', models.CharField(max_length=255, verbose_name='Tổng thu nhập năm (Gross annual income)')),
            ],
            options={
                'verbose_name': '7. Thu nhập năm (BAS_bruto_jaarinkomen)',
                'verbose_name_plural': '7. Thu nhập năm (BAS_bruto_jaarinkomen)',
            },
        ),
        migrations.CreateModel(
            name='BAS_huishoudgrootte',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã số lượng')),
                ('name', models.CharField(max_length=255, verbose_name='Kích thước hộ gia đình (Household size)')),
            ],
            options={
                'verbose_name': '5. Quy mô hộ gia đình (BAS_huishoudgrootte)',
                'verbose_name_plural': '5. Quy mô hộ gia đình (BAS_huishoudgrootte)',
            },
        ),
        migrations.CreateModel(
            name='BAS_voltooide_opleiding8_resp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã học vấn')),
                ('name', models.CharField(max_length=255, verbose_name='Trình độ học vấn (Education level)')),
            ],
            options={
                'verbose_name': '10. Trình độ học vấn (BAS_voltooide_opleiding8_resp)',
                'verbose_name_plural': '10. Trình độ học vấn (BAS_voltooide_opleiding8_resp)',
            },
        ),
        migrations.CreateModel(
            name='BAS_werkzaamheid_resp',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã trạng thái')),
                ('name', models.CharField(max_length=255, verbose_name='Tình trạng việc làm (Employment)')),
            ],
            options={
                'verbose_name': '2. Tình trạng việc làm (BAS_werkzaamheid_resp)',
                'verbose_name_plural': '2. Tình trạng việc làm (BAS_werkzaamheid_resp)',
            },
        ),
        migrations.CreateModel(
            name='RESP_GEM_GROOTTE',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã quy mô')),
                ('name', models.CharField(max_length=255, verbose_name='Quy mô đô thị (Municipality size)')),
            ],
            options={
                'verbose_name': '4. Quy mô đô thị (RESP_GEM_GROOTTE)',
                'verbose_name_plural': '4. Quy mô đô thị (RESP_GEM_GROOTTE)',
            },
        ),
        migrations.CreateModel(
            name='SPSS_Lifestage',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã giai đoạn')),
                ('name', models.CharField(max_length=255, verbose_name='Giai đoạn cuộc sống (Lifestage)')),
            ],
            options={
                'verbose_name': '11. Giai đoạn cuộc sống (SPSS_Lifestage)',
                'verbose_name_plural': '11. Giai đoạn cuộc sống (SPSS_Lifestage)',
            },
        ),
        migrations.CreateModel(
            name='SPSS_Regio5',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã vùng')),
                ('name', models.CharField(max_length=255, verbose_name='Vùng địa lý (Region)')),
            ],
            options={
                'verbose_name': '3. Vùng địa lý (SPSS_Regio5)',
                'verbose_name_plural': '3. Vùng địa lý (SPSS_Regio5)',
            },
        ),
    ]
