# Generated by Django 4.1.13 on 2026-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0002_afg_kinderen_huishouden_afg_sk2015_agecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_touch',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã touch point')),
                ('name', models.CharField(max_length=255, verbose_name='Tên touch point')),
            ],
            options={
                'verbose_name': '12. Touch point',
                'verbose_name_plural': '12. Touch point',
            },
        ),
        migrations.AlterModelOptions(
            name='genderid',
            options={'verbose_name': '1. Danh mục Giới tính', 'verbose_name_plural': '1. Danh mục Giới tính'},
        ),
    ]
