# Generated by Django 4.1.13 on 2026-05-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0003_type_touch_alter_genderid_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='afg_kinderen_huishouden',
        ),
        migrations.DeleteModel(
            name='AgeCategory',
        ),
        migrations.DeleteModel(
            name='BAS_huishoudgrootte',
        ),
        migrations.AlterModelOptions(
            name='resp_gem_grootte',
            options={'verbose_name': '6. Nhóm tuổi (Age)', 'verbose_name_plural': '6. Nhóm tuổi (Age)'},
        ),
    ]
