# Generated by Django 4.1.13 on 2026-05-20 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0004_delete_afg_kinderen_huishouden_delete_agecategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resp_gem_grootte',
            options={'verbose_name': '5. Quy mô hộ gia đình (BAS_huishoudgrootte)', 'verbose_name_plural': '5. Quy mô hộ gia đình (BAS_huishoudgrootte)'},
        ),
    ]
