# Generated by Django 4.1.13 on 2026-05-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0005_alter_resp_gem_grootte_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resp_gem_grootte',
            options={'verbose_name': '4. Quy mô đô thị (RESP_GEM_GROOTTE)', 'verbose_name_plural': '4. Quy mô đô thị (RESP_GEM_GROOTTE)'},
        ),
    ]
