# Generated by Django 4.1.13 on 2026-05-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0006_alter_resp_gem_grootte_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RESP_GEM_GROOTTE',
        ),
    ]
