# Generated by Django 4.1.13 on 2026-05-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0007_delete_resp_gem_grootte'),
    ]

    operations = [
        migrations.CreateModel(
            name='cluster_info',
            fields=[
                ('cluster_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Cluster information',
                'verbose_name_plural': 'Cluster information',
            },
        ),
        migrations.AddField(
            model_name='type_touch',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
