# Generated by Django 4.1.13 on 2026-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctmj', '0008_cluster_info_type_touch_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster_info',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên cụm'),
        ),
        migrations.AlterField(
            model_name='cluster_info',
            name='description',
            field=models.TextField(verbose_name='Mô tả cụm'),
        ),
    ]
